### PR TITLE
Feature/restructure json input and output

### PR DESCRIPTION
**Pull request by onlyjsmith**
The original `test_req.json` (and the function that ran it) expected JSON in an a valid, but unusual structure. 

I've added some notes to explain the difference [here](https://github.com/disarm-platform/functions-for-openfaas/wiki/Structuring-JSON)

**Steps to adapt this repo:**

- [x] change the `test_req.json` format
- [x] check the code which reads the params still works properly
- [ ] adapt the output code to write back JSON in the same format

### CODE REVIEW

**Comment by onlyjsmith** [comment]
I've made the first 2 changes required, but in looking at the last one I think it comes from the DiSARM `gears` code, so need to think about how to best handle. 

I'd suggest changing the return value of the `adaptive_prototype_0` function: the implications depend on how many other functions are using the same code, and whether they know which version of the `gears` code they're expecting...

**Comment by onlyjsmith** [comment]
🧨 Don't merge this one and #9!

**Comment by HughSt** [comment]
Thanks @onlyjsmith - we had made a mental note of the need to change this last week, but were trying to get a working version of the function deployed urgently for use by the Samoa team..Thanks for formally noting/explaining as an issue here

**Comment by HughSt** [comment]
@onlyjsmith is there any reason why we shouldn't be passing the spatial data in as a geojson? i.e.

```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
"value": 13
},
      "geometry": {
        "type": "Point",
        "coordinates": [
          27.07,
          -12.89
        ]
      }
    }
  ]
}
```
as opposed to your recommendation
```
[
  {
    "lat": -12.89,
    "lng": 27.07,
    "value": 13
  },
  {
    "lat": 21,
    "lng": 22,
    "value": 23
  }
]
```

**Comment by onlyjsmith** [comment]
None - your suggestion is better. 

I was trying the simplest change first, but routinely handling geographic JSON as `GeoJSON` (for input and output) is a _much_ better approach

**Pull request merged**
